services:
  sunnah-record:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sunnah_record_app
    restart: always
    network_mode: host
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL:-postgresql://shenron:abirmallik76922247@127.0.0.1:5432/sunnah_db}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://thesunnahrecord.abirmallik.website}
